=== luozhiyua/SOE_hw/src/main/java/org/example/CourseReport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.example.com/courseReport"
            targetNamespace="http://www.example.com/courseReport"
            elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="CourseInfoType">
        <xsd:sequence>
            <xsd:element name="CourseId" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="StuGraInfoType">
        <xsd:sequence>
            <xsd:element name="StudentID" type="xsd:integer"/>
            <xsd:element name="UsualScore" type="xsd:integer"/>
            <xsd:element name="FinalScore" type="xsd:integer"/>
            <xsd:element name="TotalScore" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CourseGradeType">
        <xsd:sequence>
            <xsd:element name="CourseInfo" type="CourseInfoType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="StuGraInfo" type="StuGraInfoType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="CourseReportType">
        <xsd:sequence>
            <xsd:element name="CourseGrade" type="CourseGradeType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="CourseReport" type="CourseReportType" />

</xsd:schema>

=== luozhiyua/SOE_hw/src/main/java/org/example/XML4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CourseReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/courseReport CourseReport.xsd" xmlns="http://www.example.com/courseReport">
  <CourseGrade>
    <CourseInfo>
      <CourseId>16</CourseId>
    </CourseInfo>
    <StuGraInfo>
      <StudentID>205622945</StudentID>
      <UsualScore>72</UsualScore>
      <FinalScore>93</FinalScore>
      <TotalScore>86</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201739469</StudentID>
      <UsualScore>84</UsualScore>
      <FinalScore>63</FinalScore>
      <TotalScore>69</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>209933038</StudentID>
      <UsualScore>77</UsualScore>
      <FinalScore>52</FinalScore>
      <TotalScore>59</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201048020</StudentID>
      <UsualScore>67</UsualScore>
      <FinalScore>51</FinalScore>
      <TotalScore>55</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200708274</StudentID>
      <UsualScore>42</UsualScore>
      <FinalScore>52</FinalScore>
      <TotalScore>49</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>211250218</StudentID>
      <UsualScore>80</UsualScore>
      <FinalScore>22</FinalScore>
      <TotalScore>39</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>202811024</StudentID>
      <UsualScore>3</UsualScore>
      <FinalScore>38</FinalScore>
      <TotalScore>27</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200097564</StudentID>
      <UsualScore>3</UsualScore>
      <FinalScore>14</FinalScore>
      <TotalScore>10</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>208191041</StudentID>
      <UsualScore>1</UsualScore>
      <FinalScore>2</FinalScore>
      <TotalScore>1</TotalScore>
    </StuGraInfo>
  </CourseGrade>
  <CourseGrade>
    <CourseInfo>
      <CourseId>83</CourseId>
    </CourseInfo>
    <StuGraInfo>
      <StudentID>211250218</StudentID>
      <UsualScore>85</UsualScore>
      <FinalScore>74</FinalScore>
      <TotalScore>77</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201739469</StudentID>
      <UsualScore>45</UsualScore>
      <FinalScore>76</FinalScore>
      <TotalScore>66</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>208191041</StudentID>
      <UsualScore>61</UsualScore>
      <FinalScore>65</FinalScore>
      <TotalScore>63</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200097564</StudentID>
      <UsualScore>85</UsualScore>
      <FinalScore>53</FinalScore>
      <TotalScore>62</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200708274</StudentID>
      <UsualScore>77</UsualScore>
      <FinalScore>41</FinalScore>
      <TotalScore>51</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>205622945</StudentID>
      <UsualScore>53</UsualScore>
      <FinalScore>40</FinalScore>
      <TotalScore>43</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>202811024</StudentID>
      <UsualScore>71</UsualScore>
      <FinalScore>30</FinalScore>
      <TotalScore>42</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>209933038</StudentID>
      <UsualScore>20</UsualScore>
      <FinalScore>44</FinalScore>
      <TotalScore>36</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201048020</StudentID>
      <UsualScore>4</UsualScore>
      <FinalScore>46</FinalScore>
      <TotalScore>33</TotalScore>
    </StuGraInfo>
  </CourseGrade>
  <CourseGrade>
    <CourseInfo>
      <CourseId>36</CourseId>
    </CourseInfo>
    <StuGraInfo>
      <StudentID>202811024</StudentID>
      <UsualScore>93</UsualScore>
      <FinalScore>97</FinalScore>
      <TotalScore>95</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>211250218</StudentID>
      <UsualScore>89</UsualScore>
      <FinalScore>90</FinalScore>
      <TotalScore>89</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200097564</StudentID>
      <UsualScore>44</UsualScore>
      <FinalScore>82</FinalScore>
      <TotalScore>70</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>208191041</StudentID>
      <UsualScore>64</UsualScore>
      <FinalScore>59</FinalScore>
      <TotalScore>60</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201739469</StudentID>
      <UsualScore>68</UsualScore>
      <FinalScore>28</FinalScore>
      <TotalScore>40</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201048020</StudentID>
      <UsualScore>26</UsualScore>
      <FinalScore>37</FinalScore>
      <TotalScore>33</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>205622945</StudentID>
      <UsualScore>31</UsualScore>
      <FinalScore>26</FinalScore>
      <TotalScore>27</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200708274</StudentID>
      <UsualScore>28</UsualScore>
      <FinalScore>11</FinalScore>
      <TotalScore>16</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>209933038</StudentID>
      <UsualScore>9</UsualScore>
      <FinalScore>17</FinalScore>
      <TotalScore>14</TotalScore>
    </StuGraInfo>
  </CourseGrade>
  <CourseGrade>
    <CourseInfo>
      <CourseId>54</CourseId>
    </CourseInfo>
    <StuGraInfo>
      <StudentID>202811024</StudentID>
      <UsualScore>87</UsualScore>
      <FinalScore>88</FinalScore>
      <TotalScore>87</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200708274</StudentID>
      <UsualScore>56</UsualScore>
      <FinalScore>88</FinalScore>
      <TotalScore>78</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>211250218</StudentID>
      <UsualScore>15</UsualScore>
      <FinalScore>83</FinalScore>
      <TotalScore>62</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201739469</StudentID>
      <UsualScore>5</UsualScore>
      <FinalScore>76</FinalScore>
      <TotalScore>54</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>208191041</StudentID>
      <UsualScore>3</UsualScore>
      <FinalScore>70</FinalScore>
      <TotalScore>49</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201048020</StudentID>
      <UsualScore>27</UsualScore>
      <FinalScore>48</FinalScore>
      <TotalScore>41</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>205622945</StudentID>
      <UsualScore>34</UsualScore>
      <FinalScore>42</FinalScore>
      <TotalScore>39</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>209933038</StudentID>
      <UsualScore>31</UsualScore>
      <FinalScore>21</FinalScore>
      <TotalScore>24</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200097564</StudentID>
      <UsualScore>18</UsualScore>
      <FinalScore>3</FinalScore>
      <TotalScore>7</TotalScore>
    </StuGraInfo>
  </CourseGrade>
  <CourseGrade>
    <CourseInfo>
      <CourseId>55</CourseId>
    </CourseInfo>
    <StuGraInfo>
      <StudentID>201048020</StudentID>
      <UsualScore>89</UsualScore>
      <FinalScore>83</FinalScore>
      <TotalScore>84</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200708274</StudentID>
      <UsualScore>65</UsualScore>
      <FinalScore>72</FinalScore>
      <TotalScore>69</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>209933038</StudentID>
      <UsualScore>95</UsualScore>
      <FinalScore>41</FinalScore>
      <TotalScore>57</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>208191041</StudentID>
      <UsualScore>90</UsualScore>
      <FinalScore>31</FinalScore>
      <TotalScore>48</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>200097564</StudentID>
      <UsualScore>22</UsualScore>
      <FinalScore>59</FinalScore>
      <TotalScore>47</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>201739469</StudentID>
      <UsualScore>87</UsualScore>
      <FinalScore>29</FinalScore>
      <TotalScore>46</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>211250218</StudentID>
      <UsualScore>73</UsualScore>
      <FinalScore>27</FinalScore>
      <TotalScore>40</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>202811024</StudentID>
      <UsualScore>85</UsualScore>
      <FinalScore>2</FinalScore>
      <TotalScore>26</TotalScore>
    </StuGraInfo>
    <StuGraInfo>
      <StudentID>205622945</StudentID>
      <UsualScore>21</UsualScore>
      <FinalScore>21</FinalScore>
      <TotalScore>21</TotalScore>
    </StuGraInfo>
  </CourseGrade>
</CourseReport>
